plugins:

    puppet_plugin:
        derived_from: cloudify.plugins.agent_plugin
        properties:
            url: https://github.com/Fewbytes/cloudify-puppet-plugin/archive/feature/CFY-596-standalone-puppet.zip
            # folder: cloudify-plugin-puppet

imports:
    - cloudify.openstack
    - puppet-type.yaml

blueprint:
    name: puppet-standalone-system-test
    nodes:
        -
            name: server-for-puppet-standalone
            type: cloudify.openstack.server
            properties:
                install_agent: true
                worker_config:
                    port: 22
                    user: ubuntu
                    key: ~/.ssh/cloudify-agents-kp.pem
                server:
                    # name: puppet-web-server
                    # image_name: [Enter-Image-Name]
                    # flavor_name: [Enter-Flavor-Name]
                    # security_groups: ['cloudify-sg-agents', 'puppet_sg']
            relationships:
                -   type: cloudify.openstack.server_connected_to_floating_ip
                    target: ip
                -   type: cloudify.relationships.connected_to
                    target: puppet_sg
        -
            name: puppet_node_one
            type: cloudify.types.puppet.web_server
            properties:
                port: 8080
                puppet_config:
                    environment: e1
                    node_name_prefix: pfx-
                    node_name_suffix: .puppet.example.com
                    modules:
                        - puppetlabs-apache
                        - puppetlabs-concat
                        - puppetlabs-stdlib
                        - puppetlabs-vcsrepo
                    execute:
                        configure: |
                            package{'git':}
                            ->
                            vcsrepo{$cloudify_local_repo:
                              ensure => present,
                              provider => git,
                              source   => 'https://github.com/Fewbytes/cosmo-tester-puppet-downloadable.git',
                            }
                        start: |
                            class{'cloudify_hello_world':
                            }
            relationships:
                -
                    type: cloudify.relationships.contained_in
                    target: server-for-puppet-standalone
        ### Alternative ### ### You can put your manifests in a .tar.gz in
        ### Alternative ### ### the blueprint folder.
        ### Alternative ### -
        ### Alternative ###     name: puppet_node_two
        ### Alternative ###     type: cloudify.types.puppet.app_server
        ### Alternative ###     properties:
        ### Alternative ###         port: 8080
        ### Alternative ###         puppet_config:
        ### Alternative ###             environment: e1
        ### Alternative ###             node_name_prefix: pfx-
        ### Alternative ###             node_name_suffix: .puppet.example.com
        ### Alternative ###             download: /manifests.tar.gz
        ### Alternative ###             manifest:
        ### Alternative ###                 start: manifests/site.pp

        ### Alternative ###     relationships:
        ### Alternative ###         -
        ### Alternative ###             type: cloudify.relationships.contained_in
        ### Alternative ###             target: server-for-puppet-standalone

        -   name: ip
            type: cloudify.openstack.floatingip
        -   name: puppet_sg
            type: cloudify.openstack.security_group
            properties:
                security_group:
                    name: puppet_sg
                rules:
                    -   remote_ip_prefix: 0.0.0.0/0
                        port: 22
                    -   remote_ip_prefix: 0.0.0.0/0
                        port: 8080
